name: Unkempt Thoughts
description: >
    Programming, C++
about: >

url: "https://dyniusz.github.io"
baseurl: "/blog" 
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate,  jekyll-gist]

paginate: 3

logo:             logo.png
disqus_shortname:
